// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/vsapiens/gocc-ducklang/token"
)

const (
	NoState    = -1
	NumStates  = 51
	NumSymbols = 57
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: 'v'
1: 'a'
2: 'r'
3: 'i'
4: 'f'
5: 'e'
6: 'l'
7: 's'
8: 'e'
9: 'p'
10: 'r'
11: 'i'
12: 'n'
13: 't'
14: 'i'
15: 'n'
16: 't'
17: 'f'
18: 'l'
19: 'o'
20: 'a'
21: 't'
22: 'p'
23: 'r'
24: 'o'
25: 'g'
26: 'r'
27: 'a'
28: 'm'
29: '>'
30: '<'
31: '<'
32: '>'
33: ':'
34: ';'
35: ','
36: '{'
37: '}'
38: '='
39: '('
40: ')'
41: '+'
42: '-'
43: '*'
44: '/'
45: '.'
46: '"'
47: ' '
48: '"'
49: ' '
50: '\t'
51: '\n'
52: '\r'
53: 'A'-'Z'
54: 'a'-'z'
55: '0'-'9'
56: .
*/
